#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    dic={}
    count=0
    for color in ar:
        if color in dic:
            dic[color]+=1
        else:
            dic[color]=1
    for key in dic:
        if dic[key]>=2:
            count+=dic[key]//2
    return count
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
